// src/data.js

export const cardData = [
  {
    id: 1,
    imageUrl:
      "https://i.pinimg.com/236x/7b/a2/61/7ba261004d2756510b2ceb30ed20f2c0.jpg",
    productName: "Elegant Sofa",
    markedPrice: "1400",
    sellingPrice: "1000",
    vendor: "Urban Furnishings",
    mainCategory: "Furnitures",
    category: "Sofa Sets",
    brand: "Elegance",
  },
  {
    id: 2,
    imageUrl:
      "https://i.pinimg.com/236x/ac/41/86/ac4186b14d6baecf0ca6138d770838e5.jpg",
    productName: "Table Top",
    markedPrice: "1200",
    sellingPrice: "800",
    vendor: "Furniture Galore",
    mainCategory: "Furnitures",
    category: "Home Furniture",
    brand: "Top Table",
  },
  {
    id: 3,
    imageUrl:
      "https://i.pinimg.com/236x/75/3c/c1/753cc1e0775e2bebdb5cffaf842c3f7a.jpg",
    productName: "Vintage Lamp",
    markedPrice: "900",
    sellingPrice: "700",
    vendor: "Home Decors",
    mainCategory: "Furnitures",
    category: "House Decor",
    brand: "Vintage",
  },
  {
    id: 4,
    imageUrl:
      "https://i.pinimg.com/236x/ce/5a/5c/ce5a5c8b0dfd91ed0eb52d9867d96d54.jpg",
    productName: "Wooden Chair",
    markedPrice: "1100",
    sellingPrice: "900",
    vendor: "Design Elements",
    mainCategory: "Furnitures",
    category: "Home Furniture",
    brand: "WoodWorks",
  },
  {
    id: 5,
    imageUrl:
      "https://i.pinimg.com/236x/5a/fa/60/5afa60e00dd47a34a28e0b0664342af3.jpg",
    productName: "Wooden Closet",
    markedPrice: "1500",
    sellingPrice: "1100",
    vendor: "Furniture Hub",
    mainCategory: "Furnitures",
    category: "Storage",
    brand: "ClosetPro",
  },
  {
    id: 6,
    imageUrl:
      "https://i.pinimg.com/236x/7d/92/97/7d929794f5f7a08d2d2b95276b707529.jpg",
    productName: "Royal Bed",
    markedPrice: "2000",
    sellingPrice: "1800",
    vendor: "Sleep Well",
    mainCategory: "Furnitures",
    category: "Beds",
    brand: "RoyalSleep",
  },
  {
    id: 7,
    imageUrl:
      "https://i.pinimg.com/236x/5d/86/ba/5d86ba2ad186a0a5fc7d02904129cabb.jpg",
    productName: "Decorative Vase",
    markedPrice: "600",
    sellingPrice: "500",
    vendor: "Decor Delights",
    mainCategory: "Furnitures",
    category: "Home & Decor",
    brand: "VaseDecor",
  },
  {
    id: 8,
    imageUrl:
      "https://i.pinimg.com/236x/5d/86/ba/5d86ba2ad186a0a5fc7d02904129cabb.jpg",
    productName: "Dining Table",
    markedPrice: "1300",
    sellingPrice: "1100",
    vendor: "Elegant Furnishings",
    mainCategory: "Furnitures",
    category: "Kitchen Furniture",
    brand: "DiningElegance",
  },
  {
    id: 9,
    imageUrl:
      "https://i.pinimg.com/236x/08/a1/d7/08a1d7d622e0cb84f7fafa0f6bfa6db7.jpg",
    productName: "Coffee Table",
    markedPrice: "1800",
    sellingPrice: "1500",
    vendor: "Urban Outfitters",
    mainCategory: "Furnitures",
    category: "Home Furniture",
    brand: "UrbanTable",
  },
  {
    id: 10,
    imageUrl:
      "https://i.pinimg.com/236x/1f/e2/c4/1fe2c4f88ad35d5fc2341d6faebe19a9.jpg",
    productName: "Classic Bookshelf",
    markedPrice: "2200",
    sellingPrice: "1900",
    vendor: "Book Nook",
    mainCategory: "Furnitures",
    category: "Storage",
    brand: "ClassicShelf",
  },
  {
    id: 11,
    imageUrl:
      "https://i.pinimg.com/236x/e4/d4/fc/e4d4fc6d987c07ec9f58924d96db0822.jpg",
    productName: "Wooden Shelves",
    markedPrice: "2500",
    sellingPrice: "2300",
    vendor: "Akon Furniture",
    mainCategory: "Furnitures",
    category: "Storage",
    brand: "WoodenCraft",
  },
  {
    id: 12,
    imageUrl:
      "https://i.pinimg.com/236x/c4/f6/fe/c4f6fe9685034afe9635c90c6afc0a86.jpg",
    productName: "Luxury Sofa Set",
    markedPrice: "3000",
    sellingPrice: "2700",
    vendor: "Luxury Living",
    mainCategory: "Furnitures",
    category: "Living Room ",
    brand: "LuxuryComfort",
  },
  {
    id: 13,
    imageUrl:
      "https://i.pinimg.com/236x/9c/e1/c3/9ce1c34732c856b234fffbbd184e349c.jpg",
    productName: "Sofa Set",
    markedPrice: "900",
    sellingPrice: "700",
    vendor: "Furniture World",
    mainCategory: "Furnitures",
    category: "Living Room",
    brand: "ComfortSofa",
  },
  {
    id: 14,
    imageUrl:
      "https://i.pinimg.com/236x/4b/ae/62/4bae6221913e340161fcda55165835f0.jpg",
    productName: "Office Desk",
    markedPrice: "1600",
    sellingPrice: "1400",
    vendor: "Office Essentials",
    mainCategory: "Furnitures",
    category: "Office Desk",
    brand: "OfficeWorks",
  },
  {
    id: 15,
    imageUrl:
      "https://i.pinimg.com/236x/48/ed/3a/48ed3a66e40d9f5a78b9a8799b18c6af.jpg",
    productName: "Modern Armchair",
    markedPrice: "500",
    sellingPrice: "400",
    vendor: "Comfort Zone",
    mainCategory: "Furnitures",
    category: "Chair",
    brand: "ModernComfort",
  },
  {
    id: 16,
    imageUrl:
      "https://i.pinimg.com/236x/d8/90/d6/d890d69768fbe7da81690c64031355fb.jpg",
    productName: "Cozy Armchair",
    markedPrice: "1800",
    sellingPrice: "1500",
    vendor: "Comfort Zone",
    mainCategory: "Furnitures",
    category: "Arm Chair",
    brand: "CozyComfort",
  },
  {
    id: 17,
    imageUrl:
      "https://i.pinimg.com/236x/d8/90/d6/d890d69768fbe7da81690c64031355fb.jpg",
    productName: "Office Table",
    markedPrice: "1800",
    sellingPrice: "1500",
    vendor: "Comfort Zone",
    category: "Office Furniture",
    mainCategory: "Furnitures",
    brand: "OfficePro",
  },
  {
    id: 18,
    imageUrl:
      "https://i.pinimg.com/236x/57/c8/04/57c80445adbe0e09b6f68cca09aa9051.jpg",
    productName: "Office Chairs",
    markedPrice: "1800",
    sellingPrice: "1500",
    vendor: "Office Essentials",
    mainCategory: "Furnitures",
    category: "Office Furniture",
    brand: "ChairWorks",
  },
  {
    id: 19,
    imageUrl: "https://example.com/image-url-19.jpg",
    productName: "Fitness Smart Band",
    markedPrice: "180",
    sellingPrice: "150",
    vendor: "FitTech Solutions",
    mainCategory: "Wearables",
    category: "Fitness Bands",
    brand: "FitBand",
  },
  {
    id: 20,
    imageUrl: "https://example.com/image-url-20.jpg",
    productName: "Smartphone Watch",
    markedPrice: "250",
    sellingPrice: "200",
    vendor: "Tech Wearables Ltd.",
    mainCategory: "Wearables",
    category: "Smartwatches",
    brand: "Tech Watch",
  },
  {
    id: 21,
    imageUrl: "https://example.com/image-url-21.jpg",
    productName: "Bluetooth Headphones",
    markedPrice: "120",
    sellingPrice: "100",
    vendor: "AudioTech Gear",
    mainCategory: "Wearables",
    category: "Headphones",
    brand: "AudioWave",
  },
  {
    id: 22,
    imageUrl: "https://example.com/image-url-22.jpg",
    productName: "Activity Tracker",
    markedPrice: "150",
    sellingPrice: "120",
    vendor: "HealthTrack Tech",
    mainCategory: "Wearables",
    category: "Activity Trackers",
    brand: "HealthTrack",
  },
  {
    id: 23,
    imageUrl: "https://example.com/image-url-23.jpg",
    productName: "Wireless Earphones",
    markedPrice: "90",
    sellingPrice: "70",
    vendor: "SoundTech",
    mainCategory: "Wearables",
    category: "Earphones",
    brand: "SoundX",
  },
  {
    id: 24,
    imageUrl: "https://example.com/image-url-24.jpg",
    productName: "Virtual Reality Headset",
    markedPrice: "400",
    sellingPrice: "350",
    vendor: "VR Tech Solutions",
    mainCategory: "Wearables",
    category: "VR Headsets",
    brand: "VR Experience",
  },
  {
    id: 25,
    imageUrl: "https://example.com/image-url-25.jpg",
    productName: "Smart Jewelry",
    markedPrice: "300",
    sellingPrice: "280",
    vendor: "JewelTech",
    mainCategory: "Wearables",
    category: "Jewelry",
    brand: "JewelSmart",
  },
  {
    id: 26,
    imageUrl: "https://example.com/image-url-26.jpg",
    productName: "Smart Clothing",
    markedPrice: "200",
    sellingPrice: "180",
    vendor: "TechWear Inc.",
    mainCategory: "Wearables",
    category: "Smart Clothing",
    brand: "TechStyle",
  },
  {
    id: 27,
    imageUrl: "https://example.com/image-url-27.jpg",
    productName: "Fitness Smart Scale",
    markedPrice: "120",
    sellingPrice: "100",
    vendor: "FitScale",
    mainCategory: "Wearables",
    category: "Fitness Gadgets",
    brand: "FitScale Pro",
  },
  {
    id: 28,
    imageUrl: "https://example.com/image-url-28.jpg",
    productName: "Sleep Tracker",
    markedPrice: "80",
    sellingPrice: "60",
    vendor: "SleepTech",
    mainCategory: "Wearables",
    category: "Sleep Devices",
    brand: "Sleep Monitor",
  },
  {
    id: 29,
    imageUrl: "https://example.com/image-url-29.jpg",
    productName: "AR Glasses",
    markedPrice: "600",
    sellingPrice: "500",
    vendor: "AR Tech",
    mainCategory: "Wearables",
    category: "Augmented Reality",
    brand: "AR Vision",
  },
  {
    id: 30,
    imageUrl: "https://example.com/image-url-30.jpg",
    productName: "Smart Ring",
    markedPrice: "150",
    sellingPrice: "120",
    vendor: "RingTech",
    mainCategory: "Wearables",
    category: "Smart Rings",
    brand: "SmartRing",
  },
  {
    id: 31,
    imageUrl:
      "https://i.pinimg.com/236x/c4/7e/b4/c47eb4605a87a3ce1d03394b864b1e94.jpg",
    productName: "Spaghetti Carbonara",
    markedPrice: "15",
    sellingPrice: "12",
    vendor: "Italian Delights",
    mainCategory: "Foods",
    category: "Lunch",
    brand: "Italian Delights",
  },

  {
    id: 32,
    imageUrl:
      "https://i.pinimg.com/236x/7f/5d/73/7f5d73f7d2b7e6d276b28e39c644759c.jpg",
    productName: "Papads",
    markedPrice: "15",
    sellingPrice: "12",
    vendor: "Italian Delights",
    mainCategory: "Foods",
    category: "Appetizers",
    brand: "Italian Delights",
  },
  {
    id: 33,
    imageUrl:
      "https://i.pinimg.com/236x/21/47/b2/2147b2d09a1cb9de3a5954add0a56b7a.jpg",
    productName: "Stick Cheese Potato",
    markedPrice: "15",
    sellingPrice: "12",
    vendor: "Italian Delights",
    mainCategory: "Foods",
    category: "Appetizers",
    brand: "Italian Delights",
  },
  {
    id: 34,
    imageUrl:
      "https://i.pinimg.com/564x/6c/3e/b1/6c3eb124e170c6fbd96f36c1caccab23.jpg",
    productName: "Jeera Aloo",
    markedPrice: "15",
    sellingPrice: "12",
    vendor: "Italian Delights",
    mainCategory: "Foods",
    category: "Appetizers",
    brand: "Italian Delights",
  },
  {
    id: 35,
    imageUrl:
      "https://i.pinimg.com/474x/12/5e/ab/125eabdad3eb03b554d886cdb1f8e849.jpg",
    productName: "Sushi Platter",
    markedPrice: "20",
    sellingPrice: "18",
    vendor: "Tokyo Sushi House",
    mainCategory: "Appetizer",
    category: "Sushi",
    brand: "Tokyo Sushi House",
  },
  {
    id: 36,
    imageUrl:
      "https://i.pinimg.com/236x/e6/1c/ef/e61cef37dffe3af9ce48d9e119176203.jpg",
    productName: "Steak Au Poivre",
    markedPrice: "30",
    sellingPrice: "25",
    vendor: "French Bistro",
    mainCategory: "Foods",
    category: "Pizza",
    brand: "French Bistro",
  },
  {
    id: 37,
    imageUrl:
      "https://i.pinimg.com/236x/78/a9/4b/78a94bd138ae5c3280cbc1d1eae54d8c.jpg",
    productName: "Chicken Tikka Masala",
    markedPrice: "18",
    sellingPrice: "15",
    vendor: "Spice Route",
    mainCategory: "Foods",
    category: "Curry",
    brand: "Spice Route",
  },
  {
    id: 38,
    imageUrl:
      "https://i.pinimg.com/236x/f5/f4/9d/f5f49dea66fcf93b932c8238b68e4f5e.jpg",
    productName: "Margherita Pizza",
    markedPrice: "12",
    sellingPrice: "10",
    vendor: "Pizza Planet",
    mainCategory: "Foods",
    category: "Pizza",
    brand: "Pizza Planet",
  },
  {
    id: 39,
    imageUrl:
      "https://i.pinimg.com/474x/a7/86/0e/a7860efcbcd2491a5f5f92a57082eaf7.jpg",
    productName: "Hamburger Deluxe",
    markedPrice: "8",
    sellingPrice: "6",
    vendor: "Burger Joint",
    mainCategory: "Foods",
    category: "Burgers",
    brand: "Burger Joint",
  },
  {
    id: 40,
    imageUrl:
      "https://i.pinimg.com/236x/93/cf/f1/93cff1a617e36a2f35ec7104cbb1ce1e.jpg",
    productName: "Chicken Rice",
    markedPrice: "8",
    sellingPrice: "6",
    vendor: "Delicious Kitchen",
    mainCategory: "Foods",
    category: "Main Course",
    brand: "Burger Joint",
  },
  {
    id: 41,
    imageUrl:
      "https://i.pinimg.com/236x/0b/5e/b4/0b5eb439a0fe2c71aa7b427d3402e1ea.jpg",
    productName: "Chicken MoMo",
    markedPrice: "8",
    sellingPrice: "6",
    vendor: "Delicious Kitchen",
    mainCategory: "Foods",
    category: "Main Course",
    brand: "Burger Joint",
  },
  {
    id: 42,
    imageUrl:
      "https://i.pinimg.com/564x/c0/b5/a5/c0b5a5417f085d65169ade3bc3eb3a79.jpg",
    productName: "Crepes Soufflees",
    markedPrice: "8",
    sellingPrice: "6",
    vendor: "Delicious Kitchen",
    mainCategory: "Foods",
    category: "Deserts",
    brand: "Burger Joint",
  },
  {
    id: 43,
    imageUrl:
      "https://i.pinimg.com/236x/ae/12/51/ae1251fe90d10cd86db6f8983d4eef1c.jpg",
    productName: "Chocolate Pastry",
    markedPrice: "8",
    sellingPrice: "6",
    vendor: "Bakery Point",
    mainCategory: "Foods",
    category: "Cakes & Pastry",
    brand: "Bakery Point",
  },
  {
    id: 44,
    imageUrl:
      "https://i.pinimg.com/236x/ae/12/51/ae1251fe90d10cd86db6f8983d4eef1c.jpg",
    productName: "Cheese Cake",
    markedPrice: "8",
    sellingPrice: "6",
    vendor: "Bakery Point",
    mainCategory: "Foods",
    category: "Cakes & Pastry",
    brand: "Bakery Point",
  },
];

// categoryData
export const categoryData = {
  Wearables: {
    title: "Wearables",
    description:
      "Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.",
    product_tags: 600,
    brands: 400,
    vendors: 160,
    campaigns: 50,
  },
  Foods: {
    title: "Foods",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    product_tags: 200,
    brands: 150,
    vendors: 80,
    campaigns: 20,
  },
  Furnitures: {
    title: "Furnitures",
    description:
      "Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius turpis et commodo pharetra.",
    product_tags: 300,
    brands: 250,
    vendors: 120,
    campaigns: 30,
  },
  Electronics: {
    title: "Electronics",
    description:
      "Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis.",
    product_tags: 500,
    brands: 350,
    vendors: 200,
    campaigns: 40,
  },
  Computers: {
    title: "Computers",
    description:
      "Fusce neque. Nulla facilisis, risus in hendrerit gravida, justo velit ultricies ligula, ut convallis orci orci.",
    product_tags: 450,
    brands: 300,
    vendors: 180,
    campaigns: 35,
  },
  Mobiles: {
    title: "Mobiles",
    description:
      "Etiam vitae tortor. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh.",
    product_tags: 550,
    brands: 370,
    vendors: 190,
    campaigns: 45,
  },
};
