// src/data.js

export const cardData = [
  {
    id: 1,
    imageUrl:
      "https://i.pinimg.com/564x/76/e6/09/76e609741463d711e53abfc3d73fc1ed.jpg",
    videoUrl:
      "https://videos.pexels.com/video-files/6467633/6467633-sd_960_506_25fps.mp4",
    productName: "Elegant Sofa",
    productSlug: "elegant_sofa",
    markedPrice: "1400",
    sellingPrice: "1000",
    vendor: "Urban Furnishings",
    vendorSlug: "urban_furnishings",
    mainCategory: "Furnitures",
    category: "Sofa Sets",
    brand: "Elegance",
  },
  {
    id: 2,
    imageUrl:
      "https://i.pinimg.com/236x/ac/41/86/ac4186b14d6baecf0ca6138d770838e5.jpg",
    productName: "Table Top",
    productSlug: "table_top",
    markedPrice: "1200",
    sellingPrice: "800",
    vendor: "Furniture Galore",
    vendorSlug: "furniture_galore",
    mainCategory: "Furnitures",
    category: "Home Furniture",
    brand: "Top Table",
  },
  {
    id: 3,
    imageUrl:
      "https://i.pinimg.com/236x/75/3c/c1/753cc1e0775e2bebdb5cffaf842c3f7a.jpg",
    productName: "Vintage Lamp",
    productSlug: "vintage_lamp",
    markedPrice: "900",
    sellingPrice: "700",
    vendor: "Home Decors",
    vendorSlug: "home_decors",
    mainCategory: "Furnitures",
    category: "House Decor",
    brand: "Vintage",
  },
  {
    id: 4,
    imageUrl:
      "https://i.pinimg.com/236x/ce/5a/5c/ce5a5c8b0dfd91ed0eb52d9867d96d54.jpg",
    productName: "Wooden Chair",
    productSlug: "wooden_chair",
    markedPrice: "1100",
    sellingPrice: "900",
    vendor: "Design Elements",
    vendorSlug: "design_elements",
    mainCategory: "Furnitures",
    category: "Home Furniture",
    brand: "WoodWorks",
  },
  {
    id: 5,
    imageUrl:
      "https://i.pinimg.com/236x/5a/fa/60/5afa60e00dd47a34a28e0b0664342af3.jpg",
    productName: "Wooden Closet",
    productSlug: "wooden_closet",
    markedPrice: "1500",
    sellingPrice: "1100",
    vendor: "Furniture Hub",
    vendorSlug: "furniture_hub",
    mainCategory: "Furnitures",
    category: "Storage",
    brand: "ClosetPro",
  },
  {
    id: 6,
    imageUrl:
      "https://i.pinimg.com/236x/7d/92/97/7d929794f5f7a08d2d2b95276b707529.jpg",
    productName: "Royal Bed",
    productSlug: "royal_bed",
    markedPrice: "2000",
    sellingPrice: "1800",
    vendor: "Sleep Well",
    vendorSlug: "sleep_well",
    mainCategory: "Furnitures",
    category: "Beds",
    brand: "RoyalSleep",
  },
  {
    id: 7,
    imageUrl:
      "https://i.pinimg.com/236x/5d/86/ba/5d86ba2ad186a0a5fc7d02904129cabb.jpg",
    productName: "Decorative Vase",
    productSlug: "decorative_vase",
    markedPrice: "600",
    sellingPrice: "500",
    vendor: "Decor Delights",
    vendorSlug: "decor_delights",
    mainCategory: "Furnitures",
    category: "Home & Decor",
    brand: "VaseDecor",
  },
  {
    id: 8,
    imageUrl:
      "https://i.pinimg.com/236x/5d/86/ba/5d86ba2ad186a0a5fc7d02904129cabb.jpg",
    productName: "Dining Table",
    productSlug: "dining_table",
    markedPrice: "1300",
    sellingPrice: "1100",
    vendor: "Elegant Furnishings",
    vendorSlug: "elegant_furnishings",
    mainCategory: "Furnitures",
    category: "Kitchen Furniture",
    brand: "DiningElegance",
  },
  {
    id: 9,
    imageUrl:
      "https://i.pinimg.com/236x/08/a1/d7/08a1d7d622e0cb84f7fafa0f6bfa6db7.jpg",
    productName: "Coffee Table",
    productSlug: "coffee_table",
    markedPrice: "1800",
    sellingPrice: "1500",
    vendor: "Urban Outfitters",
    vendorSlug: "urban_outfitters",
    mainCategory: "Furnitures",
    category: "Home Furniture",
    brand: "UrbanTable",
  },
  {
    id: 10,
    imageUrl:
      "https://i.pinimg.com/236x/1f/e2/c4/1fe2c4f88ad35d5fc2341d6faebe19a9.jpg",
    productName: "Classic Bookshelf",
    productSlug: "classic_bookshelf",
    markedPrice: "2200",
    sellingPrice: "1900",
    vendor: "Book Nook",
    vendorSlug: "book_nook",
    mainCategory: "Furnitures",
    category: "Storage",
    brand: "ClassicShelf",
  },
  {
    id: 11,
    imageUrl:
      "https://i.pinimg.com/236x/e4/d4/fc/e4d4fc6d987c07ec9f58924d96db0822.jpg",
    productName: "Wooden Shelves",
    productSlug: "wooden_shelves",
    markedPrice: "2500",
    sellingPrice: "2300",
    vendor: "Akon Furniture",
    vendorSlug: "akon_furniture",
    mainCategory: "Furnitures",
    category: "Storage",
    brand: "WoodenCraft",
  },
  {
    id: 12,
    imageUrl:
      "https://i.pinimg.com/236x/c4/f6/fe/c4f6fe9685034afe9635c90c6afc0a86.jpg",
    productName: "Luxury Sofa Set",
    productSlug: "luxury_sofa_set",
    markedPrice: "3000",
    sellingPrice: "2700",
    vendor: "Luxury Living",
    vendorSlug: "luxury_living",
    mainCategory: "Furnitures",
    category: "Living Room",
    brand: "LuxuryComfort",
  },
  {
    id: 13,
    imageUrl:
      "https://i.pinimg.com/236x/9c/e1/c3/9ce1c34732c856b234fffbbd184e349c.jpg",
    productName: "Sofa Set",
    productSlug: "sofa_set",
    markedPrice: "900",
    sellingPrice: "700",
    vendor: "Furniture World",
    mainCategory: "Furnitures",
    category: "Living Room",
    brand: "ComfortSofa",
  },
  {
    id: 14,
    imageUrl:
      "https://i.pinimg.com/236x/4b/ae/62/4bae6221913e340161fcda55165835f0.jpg",
    productName: "Office Desk",
    productSlug: "office_desk",
    markedPrice: "1600",
    sellingPrice: "1400",
    vendor: "Office Essentials",
    vendorSlug: "office_essentials",
    mainCategory: "Furnitures",
    category: "Office Desk",
    brand: "OfficeWorks",
  },
  {
    id: 15,
    imageUrl:
      "https://i.pinimg.com/236x/48/ed/3a/48ed3a66e40d9f5a78b9a8799b18c6af.jpg",
    productName: "Modern Armchair",
    productSlug: "modern_armchair",
    markedPrice: "500",
    sellingPrice: "400",
    vendor: "Comfort Zone",
    vendorSlug: "comfort_zone",
    mainCategory: "Furnitures",
    category: "Chair",
    brand: "ModernComfort",
  },
  {
    id: 16,
    imageUrl:
      "https://i.pinimg.com/236x/d8/90/d6/d890d69768fbe7da81690c64031355fb.jpg",
    productName: "Cozy Armchair",
    productSlug: "cozy_armchair",
    markedPrice: "1800",
    sellingPrice: "1500",
    vendor: "Comfort Zone",
    vendorSlug: "comfort_zone",
    mainCategory: "Furnitures",
    category: "Arm Chair",
    brand: "CozyComfort",
  },
  {
    id: 17,
    imageUrl:
      "https://i.pinimg.com/236x/d8/90/d6/d890d69768fbe7da81690c64031355fb.jpg",
    productName: "Office Table",
    productSlug: "office_table",
    markedPrice: "1800",
    sellingPrice: "1500",
    vendor: "Comfort Zone",
    vendorSlug: "comfort_zone",
    category: "Office Furniture",
    mainCategory: "Furnitures",
    brand: "OfficePro",
  },
  {
    id: 18,
    imageUrl:
      "https://i.pinimg.com/236x/57/c8/04/57c80445adbe0e09b6f68cca09aa9051.jpg",
    productName: "Office Chairs",
    productSlug: "office_chairs",
    markedPrice: "1800",
    sellingPrice: "1500",
    vendor: "Office Essentials",
    vendorSlug: "office_ essentials",
    mainCategory: "Furnitures",
    category: "Office Furniture",
    brand: "ChairWorks",
  },
  {
    id: 19,
    imageUrl:
      "https://i.pinimg.com/236x/30/4b/dc/304bdce25513536430e4ae8d30478835.jpg",
    productName: "Men's Blazer",
    productSlug: "men's_blazer",
    markedPrice: "180",
    sellingPrice: "150",
    vendor: "Elegant Apparel",
    vendorSlug: "elegant_apparel",
    mainCategory: "Wearables",
    category: "Men's Clothing",
    brand: "Raymond",
  },
  {
    id: 20,
    imageUrl:
      "https://i.pinimg.com/236x/ed/f9/47/edf94700281731272dd4fa1093fb13fc.jpg",
    productName: "Women Poncho",
    productSlug: "women_poncho",
    markedPrice: "250",
    sellingPrice: "200",
    vendor: "Elegant Apparel",
    vendorSlug: "elegant_apparel",
    mainCategory: "Wearables",
    category: "Women's Clothing",
    brand: "Tech Watch",
  },
  {
    id: 21,
    imageUrl:
      "https://i.pinimg.com/236x/74/c8/56/74c856c7899d078486377bb2be09dfed.jpg",
    productName: "Shirt",
    productSlug: "shirt",
    markedPrice: "120",
    sellingPrice: "100",
    vendor: "Elegant Apparel",
    vendorSlug: "elegant_apparel",
    mainCategory: "Wearables",
    category: "Women's Shirt",
    brand: "H&M",
  },
  {
    id: 22,
    imageUrl:
      "https://i.pinimg.com/236x/3b/a2/72/3ba2729e75a5f9f253a09f4e6841104d.jpg",
    productName: "Jacket",
    productSlug: "jacket",
    markedPrice: "150",
    sellingPrice: "120",
    vendor: "Elegant Apparel",
    mainCategory: "Wearables",
    category: "Men's Jacket",
    brand: "Elegant Apparel",
  },
  {
    id: 23,
    imageUrl:
      "https://i.pinimg.com/236x/32/58/d8/3258d8326e0a01abd4f4c817f074dd73.jpg",
    productName: "Men's Ethnic Top",
    productSlug: "men's_ethnic_top",
    markedPrice: "90",
    sellingPrice: "70",
    vendor: "Elegant Apparel",
    vendorSlug: "elegant_apparel",
    mainCategory: "Wearables",
    category: "Men's Ethnic Wear",
    brand: "Easy",
  },
  {
    id: 24,
    imageUrl:
      "https://i.pinimg.com/236x/fd/fd/d1/fdfdd1108aba0a75da70daf1e56ef3b8.jpg",
    productName: "Jeans",
    productSlug: "jeans",
    markedPrice: "400",
    sellingPrice: "350",
    vendor: "Elegant Apparel",
    vendorSlug: "elegant_apparel",
    mainCategory: "Wearables",
    category: "Women's Jeans",
    brand: "Denim",
  },
  {
    id: 25,
    imageUrl:
      "https://i.pinimg.com/236x/bb/ea/16/bbea167d29b9b259c2dc32029c1f718e.jpg",
    productName: "Jeans ",
    productSlug: "jeans",
    markedPrice: "300",
    sellingPrice: "280",
    vendor: "Elegant Apparel",
    vendorSlug: "elegant_apparel",
    mainCategory: "Wearables",
    category: "Men's Jeans",
    brand: "Denim",
  },
  {
    id: 26,
    imageUrl:
      "https://i.pinimg.com/236x/97/c6/65/97c6651d485ed4f26bc4ff7e76faebd7.jpg",
    productName: "Men's Sweater",
    productSlug: "men's_sweater",
    markedPrice: "200",
    sellingPrice: "180",
    vendor: "TechWear Inc.",
    vendorSlug: "techwear_inc",
    mainCategory: "Wearables",
    category: "Men's Formal",
    brand: "Formal Wear",
  },
  {
    id: 27,
    imageUrl:
      "https://i.pinimg.com/474x/6f/18/d7/6f18d7919759b9151ed9c41ec216a204.jpg",
    productName: "Rolex Men's Watch",
    productSlug: "rolex_men's_watch",
    markedPrice: "120",
    sellingPrice: "100",
    vendor: "FitScale",
    vendorSlug: "fitscale",
    mainCategory: "Wearables",
    category: "Men's Watches",
    brand: "FitScale Pro",
  },
  {
    id: 28,
    imageUrl:
      "https://i.pinimg.com/236x/7d/a5/08/7da508aa0ea4c14605d1065373819b25.jpg",
    productName: "Casio Men's Watch",
    productSlug: "casio_men's_watch",
    markedPrice: "80",
    sellingPrice: "60",
    vendor: "Watch Hub",
    vendorSlug: "watch_hub",
    mainCategory: "Wearables",
    category: "Men's Watches",
    brand: "Casio",
  },
  {
    id: 29,
    imageUrl:
      "https://i.pinimg.com/236x/b7/6f/b6/b76fb68e929ae8925950b7ade9e086e3.jpg",
    productName: "Rayman Singlasses",
    productSlug: "rayman_singlasses",
    markedPrice: "600",
    sellingPrice: "500",
    vendor: "Sunglasses Hub",
    vendorSlug: "sunglasses_hub",
    mainCategory: "Wearables",
    category: "Sunglasses",
    brand: "Rayman",
  },
  {
    id: 30,
    imageUrl:
      "https://i.pinimg.com/236x/1e/4d/f1/1e4df1de38d8cddf6db4a5217ed4b210.jpg",
    productName: "Avaitor Sunglasses",
    productSlug: "avaitor_sunglasses",
    markedPrice: "150",
    sellingPrice: "120",
    vendor: "Sunglasses Home",
    vendorSlug: "sunglasses_home",
    mainCategory: "Wearables",
    category: "Sunglasses",
    brand: "Avaitor",
  },
  {
    id: 31,
    imageUrl:
      "https://i.pinimg.com/236x/c4/7e/b4/c47eb4605a87a3ce1d03394b864b1e94.jpg",
    productName: "Spaghetti Carbonara",
    productSlug: "spaghetti_carbonara",
    markedPrice: "15",
    sellingPrice: "12",
    vendor: "Italian Delights",
    vendorSlug: "italian_delights",
    mainCategory: "Foods",
    category: "Lunch",
    brand: "Italian Delights",
  },
  {
    id: 32,
    imageUrl:
      "https://i.pinimg.com/236x/7f/5d/73/7f5d73f7d2b7e6d276b28e39c644759c.jpg",
    productName: "Papads",
    productSlug: "papads",
    markedPrice: "15",
    sellingPrice: "12",
    vendor: "Italian Delights",
    vendorSlug: "italian_delights",
    mainCategory: "Foods",
    category: "Appetizers",
    brand: "Italian Delights",
  },
  {
    id: 33,
    imageUrl:
      "https://i.pinimg.com/236x/21/47/b2/2147b2d09a1cb9de3a5954add0a56b7a.jpg",
    productName: "Stick Cheese Potato",
    productSlug: "stick_cheese_potato",
    markedPrice: "15",
    sellingPrice: "12",
    vendor: "Italian Delights",
    vendorSlug: "italian_delights",
    mainCategory: "Foods",
    category: "Appetizers",
    brand: "Italian Delights",
  },
  {
    id: 34,
    imageUrl:
      "https://i.pinimg.com/564x/6c/3e/b1/6c3eb124e170c6fbd96f36c1caccab23.jpg",
    productName: "Jeera Aloo",
    productSlug: "jeera_aloo",
    markedPrice: "15",
    sellingPrice: "12",
    vendor: "Italian Delights",
    vendorSlug: "italian_delights",
    mainCategory: "Foods",
    category: "Appetizers",
    brand: "Italian Delights",
  },
  {
    id: 35,
    imageUrl:
      "https://i.pinimg.com/474x/12/5e/ab/125eabdad3eb03b554d886cdb1f8e849.jpg",
    productName: "Sushi Platter",
    productSlug: "sushi_platter",
    markedPrice: "20",
    sellingPrice: "18",
    vendor: "Tokyo Sushi House",
    vendorSlug: "tokyo_sushi_house",
    mainCategory: "Appetizer",
    category: "Sushi",
    brand: "Tokyo Sushi House",
  },
  {
    id: 36,
    imageUrl:
      "https://i.pinimg.com/236x/e6/1c/ef/e61cef37dffe3af9ce48d9e119176203.jpg",
    productName: "Steak Au Poivre",
    productSlug: "steak_au_poivre",
    markedPrice: "30",
    sellingPrice: "25",
    vendor: "French Bistro",
    vendorSlug: "french_bistro",
    mainCategory: "Foods",
    category: "Pizza",
    brand: "French Bistro",
  },
  {
    id: 37,
    imageUrl:
      "https://i.pinimg.com/236x/78/a9/4b/78a94bd138ae5c3280cbc1d1eae54d8c.jpg",
    productName: "Chicken Tikka Masala",
    productSlug: "chicken_tikka_masala",
    markedPrice: "18",
    sellingPrice: "15",
    vendor: "Spice Route",
    vendorSlug: "spice_route",
    mainCategory: "Foods",
    category: "Curry",
    brand: "Spice Route",
  },
  {
    id: 38,
    imageUrl:
      "https://i.pinimg.com/236x/f5/f4/9d/f5f49dea66fcf93b932c8238b68e4f5e.jpg",
    productName: "Margherita Pizza",
    productSlug: "margherita_pizza",
    markedPrice: "12",
    sellingPrice: "10",
    vendor: "Pizza Planet",
    vendorSlug: "pizza_planet",
    mainCategory: "Foods",
    category: "Pizza",
    brand: "Pizza Planet",
  },
  {
    id: 39,
    imageUrl:
      "https://i.pinimg.com/474x/a7/86/0e/a7860efcbcd2491a5f5f92a57082eaf7.jpg",
    productName: "Hamburger Deluxe",
    productSlug: "hamburger_deluxe",
    markedPrice: "8",
    sellingPrice: "6",
    vendor: "Burger Joint",
    vendorSlug: "burger_joint",
    mainCategory: "Foods",
    category: "Burgers",
    brand: "Burger Joint",
  },
  {
    id: 40,
    imageUrl:
      "https://i.pinimg.com/236x/93/cf/f1/93cff1a617e36a2f35ec7104cbb1ce1e.jpg",
    productName: "Chicken Rice",
    productSlug: "chicken_rice",
    markedPrice: "8",
    sellingPrice: "6",
    vendor: "Delicious Kitchen",
    vendorSlug: "delicious_kitchen",
    mainCategory: "Foods",
    category: "Main Course",
    brand: "Burger Joint",
  },
  {
    id: 41,
    imageUrl:
      "https://i.pinimg.com/236x/0b/5e/b4/0b5eb439a0fe2c71aa7b427d3402e1ea.jpg",
    productName: "Chicken MoMo",
    productSlug: "chicken_momo",
    markedPrice: "8",
    sellingPrice: "6",
    vendor: "Delicious Kitchen",
    vendorSlug: "delicious_kitchen",
    mainCategory: "Foods",
    category: "Main Course",
    brand: "Burger Joint",
  },
  {
    id: 42,
    imageUrl:
      "https://i.pinimg.com/564x/c0/b5/a5/c0b5a5417f085d65169ade3bc3eb3a79.jpg",
    productName: "Crepes Soufflees",
    productSlug: "crepes_soufflees",
    markedPrice: "8",
    sellingPrice: "6",
    vendor: "Delicious Kitchen",
    vendorSlug: "delicious_kitchen",
    mainCategory: "Foods",
    category: "Deserts",
    brand: "Burger Joint",
  },
  {
    id: 43,
    imageUrl:
      "https://i.pinimg.com/236x/ae/12/51/ae1251fe90d10cd86db6f8983d4eef1c.jpg",
    productName: "Chocolate Pastry",
    productSlug: "chocolate_pastry",
    markedPrice: "8",
    sellingPrice: "6",
    vendor: "Bakery Point",
    vendorSlug: "bakery_point",
    mainCategory: "Foods",
    category: "Cakes & Pastry",
    brand: "Bakery Point",
  },
  {
    id: 44,
    imageUrl:
      "https://i.pinimg.com/236x/ae/12/51/ae1251fe90d10cd86db6f8983d4eef1c.jpg",
    productName: "Cheese Cake",
    productSlug: "cheese_cake",
    markedPrice: "8",
    sellingPrice: "6",
    vendor: "Bakery Point",
    vendorSlug: "bakery_point",
    mainCategory: "Foods",
    category: "Cakes & Pastry",
    brand: "Bakery Point",
  },
  {
    id: 45,
    imageUrl:
      "https://i.pinimg.com/236x/7d/92/97/7d929794f5f7a08d2d2b95276b707529.jpg",
    videoUrl:
      "https://videos.pexels.com/video-files/6467633/6467633-sd_960_506_25fps.mp4",
    productName: "Elegant Sofa",
    productSlug: "elegant_sofa",
    markedPrice: "1400",
    sellingPrice: "1000",
    vendor: "Urban Furnishings",
    vendorSlug: "urban_furnishings",
    mainCategory: "Furnitures",
    category: "Home Furnitures",
    brand: "Elegance",
  },
  {
    id: 46,
    imageUrl:
      "https://i.pinimg.com/236x/55/4c/fe/554cfe08070dfb7ca9c398b92841d917.jpg",
    videoUrl:
      "https://videos.pexels.com/video-files/6467633/6467633-sd_960_506_25fps.mp4",
    productName: "Table Set",
    productSlug: "table_set",
    markedPrice: "1400",
    sellingPrice: "1000",
    vendor: "Urban Furnishings",
    vendorSlug: "urban_furnishings",
    mainCategory: "Furnitures",
    category: "Office Furnitures",
    brand: "Elegance",
  },
  {
    id: 47,
    imageUrl:
      "https://i.pinimg.com/236x/49/d0/3b/49d03befc6c41f2ec0aebd0d30d7b525.jpg",
    videoUrl:
      "https://videos.pexels.com/video-files/6467633/6467633-sd_960_506_25fps.mp4",
    productName: "Team Table Set",
    productSlug: "team_table_set",
    markedPrice: "1400",
    sellingPrice: "1000",
    vendor: "Urban Furnishings",
    vendorSlug: "urban_furnishings",
    mainCategory: "Furnitures",
    category: "Office Furnitures",
    brand: "Elegance",
  },
  {
    id: 48,
    imageUrl:
      "https://i.pinimg.com/236x/f2/82/dc/f282dc5eb8efc39e86254caf15498330.jpg",
    videoUrl:
      "https://videos.pexels.com/video-files/6467633/6467633-sd_960_506_25fps.mp4",
    productName: "Single Corporate Chair",
    productSlug: "single_corporate_chair",
    markedPrice: "1400",
    sellingPrice: "1000",
    vendor: "Urban Furnishings",
    vendorSlug: "urban_furnishings",
    mainCategory: "Furnitures",
    category: "Office Chairs",
    brand: "Elegance",
  },
  {
    id: 49,
    imageUrl:
      "https://i.pinimg.com/236x/37/1b/53/371b536c969ccdc2aac39966326db332.jpg",
    videoUrl:
      "https://videos.pexels.com/video-files/6467633/6467633-sd_960_506_25fps.mp4",
    productName: "Single Bamboo Chair",
    productSlug: "single_bamboo_chair",
    markedPrice: "1400",
    sellingPrice: "1000",
    vendor: "Urban Furnishings",
    vendorSlug: "urban_furnishings",
    mainCategory: "Furnitures",
    category: "Chairs",
    brand: "Elegance",
  },
  {
    id: 50,
    imageUrl:
      "https://i.pinimg.com/236x/7c/d0/b3/7cd0b3450ff756506e29f02c6d37e606.jpg",
    videoUrl:
      "https://videos.pexels.com/video-files/6467633/6467633-sd_960_506_25fps.mp4",
    productName: "Single Bamboo Table",
    productSlug: "single_bamboo_table",
    markedPrice: "1400",
    sellingPrice: "1000",
    vendor: "Urban Furnishings",
    vendorSlug: "urban_furnishings",
    mainCategory: "Furnitures",
    category: "Tables",
    brand: "Elegance",
  },
  {
    id: 51,
    imageUrl:
      "https://i.pinimg.com/236x/fb/eb/3f/fbeb3f93bd1b260d4054107ea8de2b22.jpg",
    videoUrl:
      "https://videos.pexels.com/video-files/6467633/6467633-sd_960_506_25fps.mp4",
    productName: "TV Cabinet",
    productSlug: "tv_cabinet",
    markedPrice: "1400",
    sellingPrice: "1000",
    vendor: "Urban Furnishings",
    vendorSlug: "urban_furnishings",
    mainCategory: "Furnitures",
    category: "Design Blocks",
    brand: "Elegance",
  },
  {
    id: 52,
    imageUrl:
      "https://i.pinimg.com/474x/7e/ce/8b/7ece8b5a7e98189089f570518fe1f139.jpg",
    videoUrl:
      "https://videos.pexels.com/video-files/6467633/6467633-sd_960_506_25fps.mp4",
    productName: "Bedroom Wooden Cabinet",
    productSlug: "bedroom_Wooden_cabinet",
    markedPrice: "1400",
    sellingPrice: "1000",
    vendor: "Urban Furnishings",
    vendorSlug: "urban_furnishings",
    mainCategory: "Furnitures",
    category: "Design Blocks",
    brand: "Elegance",
  },
  {
    id: 53,
    imageUrl:
      "https://i.pinimg.com/236x/74/35/63/74356319261fc3f2e8944acdafaccf35.jpg",
    videoUrl:
      "https://videos.pexels.com/video-files/6467633/6467633-sd_960_506_25fps.mp4",
    productName: "YingYang Books Shelf",
    productSlug: "yingyang_books_shelf",
    markedPrice: "1400",
    sellingPrice: "1000",
    vendor: "Urban Furnishings",
    vendorSlug: "urban_furnishings",
    mainCategory: "Furnitures",
    category: "Design Blocks",
    brand: "Elegance",
  },
];

// categoryData
export const categoryData = {
  Wearables: {
    title: "Wearables",
    description:
      "Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.",
    product_tags: 600,
    brands: 400,
    vendors: 160,
    campaigns: 50,
  },
  Foods: {
    title: "Foods",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    product_tags: 200,
    brands: 150,
    vendors: 80,
    campaigns: 20,
  },
  Furnitures: {
    title: "Furnitures",
    description:
      "Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius turpis et commodo pharetra.",
    product_tags: 300,
    brands: 250,
    vendors: 120,
    campaigns: 30,
  },
  Electronics: {
    title: "Electronics & Accessories",
    description:
      "Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis.",
    product_tags: 500,
    brands: 350,
    vendors: 200,
    campaigns: 40,
  },
  Computers: {
    title: "Computers & Accessories",
    description:
      "Fusce neque. Nulla facilisis, risus in hendrerit gravida, justo velit ultricies ligula, ut convallis orci orci.",
    product_tags: 450,
    brands: 300,
    vendors: 180,
    campaigns: 35,
  },
  Mobiles: {
    title: "Mobiles & Accessories",
    description:
      "Etiam vitae tortor. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh.",
    product_tags: 550,
    brands: 370,
    vendors: 190,
    campaigns: 45,
  },
  Services: {
    title: "Services",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    product_tags: 200,
    brands: 150,
    vendors: 80,
    campaigns: 20,
  },
  Holidays: {
    title: "Holidays",
    description:
      "Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius turpis et commodo pharetra.",
    product_tags: 300,
    brands: 250,
    vendors: 120,
    campaigns: 30,
  },
  Appointments: {
    title: "Appointments",
    description:
      "Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis.",
    product_tags: 500,
    brands: 350,
    vendors: 200,
    campaigns: 40,
  },
};

export const responsive = {
  desktop: {
    breakpoint: { max: 3000, min: 1024 },
    items: 4,
  },
  tablet: {
    breakpoint: { max: 1023, min: 464 },
    items: 2,
  },
  mobile: {
    breakpoint: { max: 767, min: 0 },
    items: 1,
  },
};

export const CampaignCardsContent = [
  {
    title: "Loyalty Discounts",
    description: "Get discount for every purchase with us.",
    earning: "5% ",
  },

  {
    title: "Big Buy Discount",
    description: "Enjoy the best deals of the season. ",
    earning: "10% ",
  },

  {
    title: "Clearance Sale",
    description: "Yes we are clearing our stock. ",
    earning: "20% - 60%",
  },
  {
    title: "Clearance Sale",
    description: "Yes we are clearing our stock. ",
    earning: "20% - 60%",
  },
  {
    title: "Big Buy Discount",
    description: "Enjoy the best deals of the season. ",
    earning: "10% ",
  },
  {
    title: "Loyalty Discounts",
    description: "Get discount for every purchase with us.",
    earning: "5% ",
  },
];
